### ISSUE TITLE
Is there a pesq score for the DNS2020 test set(no_reverb)?

### ISSUE THREAD

**Issue by zuowanbushiwo** [heisenberg-kim/lstm_in_the_unet#1]
Hi @heisenberg-kim 
     Is there a pesq score for the DNS2020 test set(no_reverb)?
     thanks!

**Comment by heisenberg-kim** [comment]
sorry for late answer. 
float32 model has pesq score for narrow band(NB) ~3.1 / for wide band ~ 2.42
